user_auth/user_auth/urls.py
from django.contrib import admin
from django.urls import path,include
from user_auth_app import views

urlpatterns = [
    path(r'',views.index ,name = "index"),
    path('user_auth_app/',include('user_auth_app.urls')),
    path('admin/', admin.site.urls),
    
]

user_auth/user_auth_app/urls.py
from django.urls import path ,include
from user_auth_app import views

app_name = "user_auth_app"

urlpatterns = [
    path(r'',views.user_auth_index,name = "user_auth_index"),
    path(r'user_login/',views.user_login,name = "user_login"),
    path(r'register/',views.registration,name = "registration"),
    path(r'user_logout/',views.user_logout,name="user_logout"),
    path(r'special/',views.special,name="special"),

]

user_auth/user_auth_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete = models.CASCADE)

    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True) 


    def __str__(self):
        return self.user.username

user_auth/user_auth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_auth_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    

    password = forms.CharField(widget = forms.PasswordInput()) #form hiding the password while typing in forms

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

user_auth/user_auth_app/views.py
from django.shortcuts import render
#imports for registration 
from user_auth_app.forms import UserForm,UserProfileInfoForm

#imports for login
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect ,HttpResponse
from django.urls import reverse


# Create your views here.

def index(request):
    return render(request,'index.html')

def user_auth_index(request):
    return render(request,'user_auth_app/user_auth_index.html')


@login_required
def special(request):
    return HttpResponse("you are logged in ,Nice!") 

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



# user registration
def registration(request):
    registered = False
   

    if request.method == "POST":          #this is activated when we click submit by giving info 
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()              #saves user directly to db
            user.set_password(user.password)        #hassing the pasword
            user.save()                           #saving password in db

            profile = profile_form.save(commit = False)
            profile.user = user                      #gives one to one relation
            
            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    
    else:                             #this runs and creates instances when page is loaded 
        user_form =UserForm()
        profile_form =UserProfileInfoForm()

    


    # this return works 1st to display form without any values of its key when else executes
    # in second time after form is filled and users gives value ani clicks submit its value are filled after 
    # validation and its loads the index paf=ge with thank ypu for registering
    return render(request,'user_auth_app/registration.html',
                                    {'user_form':user_form,
                                     'profile_form':profile_form,
                                     'registered':registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        #django build in authentication
        user = authenticate(username =username ,password = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('user_auth_app:user_auth_index'))
                # if view name is passed the a colon is used
               
            
            else:
                return HttpResponse("Account Not Active")
        
        else:
            print("some one tried to login and failed")
            print(f"username :{username} and password : {password}")
            return HttpResponse("invalid login supplied!")
    else:
        return render(request, 'user_auth_app/user_login.html',{})

    # return render(request,'user_auth_app/user_login.html')

user_auth/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <style>
       body{
           font-family : 'Open Sans', sans-serif;

       } 
    </style>
    
    <title>index</title>
</head>
<body>
    
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Logo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_auth_app:user_auth_index' %}">User_Auth</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_auth_app:registration' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                        {%if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user_auth_app:user_logout' %}">Logout</a>
                            </li>
                        {%else%}
                            <li class="nav-item">
                                <a  class="nav-link"href="{% url 'user_auth_app:user_login' %}">Login</a>
                            </li>


                        {% endif %}
                    
                    
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>

        
    </div>
   
  
    <div class="container">
        {% block index_block%}
            <h1>
                Welcome this is the index page

            </h1>
           
        {% endblock %}
    </div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
</html>

user_auth/templates/user_auth_app/registration.html
<!DOCTYPE html>
    {%extends 'index.html'%}
    {% load staticfiles %}

    {%block index_block%}
        <h1>the registration page</h1>
        <div class="jumbotron">

            <!-- at first the else statement is executed as registered is false and forms are displayed with no values as 
            the value injected are empty i.e just object are created then after form is filled and
            validated the value of registered becomes true and if statement is executed -->


            {% if registered %}
                <h1>Thank you for registering! {{user_form.username}}</h1>
            {%else%}
                <h1>Register Here</h1>
                <h3>Fill Out The Form:</h3>

                <form enctype="multipart/form-data" method = "POST" >
                    
                    {{user_form.as_p}}
                    {{profile_form.as_p}}
                     {% csrf_token %}   
                    <!-- typ csrf_token jai;e submit bhand agi dinu parxa natra error auxa  -->
                    <input type="submit" value="Register">

                </form>


            {% endif %}
        </div>

    {%endblock%}

user_auth/templates/user_auth_app/user_auth_index.html
<!DOCTYPE html>
{%extends 'index.html'%}
{%load staticfiles %}

{% block index_block%}
<h1>this is the user_auth_index</h1>
{% endblock %}

user_auth/templates/user_auth_app/user_login.html
<!DOCTYPE html>
{%extends 'index.html'%}

{%block index_block%}


<div class="jumbotron">
    <h1>Please login</h1>
    <form method="POST" action="{% url 'user_auth_app:user_login'%}">
        

        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="text" name="password" placeholder="Enter Password">
        {% csrf_token %}
        <input type="Submit" name="" value="Login">

    </form>
</div>













{%endblock%}